stages:
- build
- test

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  TAG_COMMIT_LONG_SHA: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA

include:
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Container-Scanning.gitlab-ci.yml

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
  - docker
  script:
  - docker build -t $TAG_COMMIT -t $TAG_LATEST -t $TAG_COMMIT_LONG_SHA .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker push $TAG_COMMIT
  - docker push $TAG_LATEST
  - docker push $TAG_COMMIT_LONG_SHA
  only:
    refs:
      - master
    changes:
      - .gitlab-ci.yml
      - cron-run
      - docker-entrypoint.sh
      - Dockerfile